CRON:
  DAV:
    Fobi:
      widgetLoaderUri: '%env:DAV_FOBI_URI%'
      token:
        # The issuer of the token
        issuer: '%env:DAV_FOBI_ISSUER%'
        # The target domain for which the token was issued.
        audience: '%env:DAV_FOBI_AUDIENCE%'
        # Password for basic auth when contacting  server
        secret: '%env:DAV_FOBI_SECRET%'
        # Token expiration: a string which can be passed to the php DateInterval constructor
        expiresAfter: '%env:DAV_FOBI_EXPIRESAFTER%'
        rolesMapping:
          # Map flow roles to strings used in Fobi, i.e.:
          #'CRON.DazSite:DazSubscriber': 'DAZ-Abo'
          #'CRON.DazSite:ELearningUser': 'eLearning-Benutzer'
