Neos:
  Neos:
    fusion:
      autoInclude:
        CRON.DAV.Fobi: true
    userInterface:
      translation:
        autoInclude:
          'CRON.DAV.Fobi':
            - NodeTypes/*
    nodeTypes:
      groups:
        widget:
          position: 'after plugins'
          label: Widget
